### ISSUE TITLE
Cookicutter Tutorial Steps

### ISSUE THREAD

**Issue by umohnani8** [FNNDSC/cookiecutter-chrisapp#1]
After going through the tutorial, these are some of the things I think we should add to the tutorial to make it easier to follow.

1) Maybe mention that the user needs to have `virtualenv` and `virtualenvwrapper` installed.
2) Add the allowed syntax for the interactive script. For example app name cannot have `-` etc. It took me about 2 tries to get through that part because of how I was naming things.
3) The tutorial says to create a repository on the FNNDSC github and docker, need to change this to inform users to use their personal github and docker.
4) Add links to the `fnndsc/simpledsapp` and `fnndsc/simplefsapp` so users can have an idea on what to do next after their template is generated for them.
5) Mention the difference between a `ds` and a `fs` app. (I am not sure myself what the difference is and why I would chose to write one over the other)
6) More detailed instructions on how to create the Automated Build in docker.

If agreed on and with some more information, I can create a PR with these additions and changes.

**Comment by umohnani8** [comment]
@rudolphpienaar @jbernal0019 PTAL

**Comment by rudolphpienaar** [comment]
These are good suggestions. Will work on getting this done for hackathon.

**Comment by jbernal0019** [comment]
Hey @umohnani8 good work pointing out all these problems. We would really appreciate if you could make a pull request that addresses them. Here I'm going to try provide some help for each bullet point.

1. I think you can look at the README here https://github.com/FNNDSC/ChRIS_ultron_backEnd and copy from there the sections **Install virtualenv** and **Setup your virtual environments**. All this should be done only if not already done by the developer. The name of the virtual environment could better be something like _plugins_env_ or _chrisapps_env_.

2. The app name must be a valid python module name. Like described in PEP8 https://www.python.org/dev/peps/pep-0008/#package-and-module-names

3. Agree, just leave FNNDSC as an example there.

4. Agree, with some explanation for the links.

5. There are two types of ChRIS plugin apps:
     1. 'fs' plugin app. This **doesn't have an input directory** as a positional argument (does have an **output directory** though) and **always creates a 
     new feed**. So 'fs' plugins are always the single root of a pipeline or tree of plugin executions.
     2.  'ds' plugin app. **This has both input and output directories as positional arguments. It never generates a new feed**. 'ds' plugins can only be run after a 'fs' plugin or another 'ds' plugin as they require an input directory (which is the output of the previous plugin).

    So the first plugin of a pipeline would always be a 'fs' plugin and the rest would be a chain of 'ds' plugins creating files in the same single feed that was created by the root 'fs' plugin. 

 6. Not sure what extra information you would like to add here. The process itself of creating the automated build is straightforward. If you wanted to explain what an automated build is, etc... then you can link to the  dockerhub documentation like this one: https://docs.docker.com/docker-hub/builds/

Please let me know if you need anymore information
Thanks! and HTH.

**Comment by umohnani8** [comment]
Great, @jbernal0019 thanks for the info! I will open a PR in a bit with these changes :)
